### PR TITLE
Fixes NIP-64

### PR DESCRIPTION
**Pull request by larubbio**
Given a subscribers district attempt to find their circle and assign it to them.

### CODE REVIEW

**Comment by frankhuster** [comment]
Don't you **love** detatched fields? ;-)

**Comment by frankhuster** [comment]
Any way we can write an IT for that?

**Comment by frankhuster** [comment]
Other than that, lgtm.

**Comment by larubbio** [comment]
The IT would load a user via csv and see if their circle was set.  I guess I could ......

**Pull request merged**
