### PR TITLE
Fixes the language getDetachedField errors

### PR DESCRIPTION
**Pull request by frankhuster**

### CODE REVIEW

**Comment by koshalt** [comment]
test this please

**Comment by koshalt** [comment]
@frankhuster the builds now pass with the revert and 0.27.x branch. I think we should still merge this PR for good practice. What say you?

**Comment by koshalt** [comment]
test this please

**Comment by frankhuster** [comment]
"Ha!" is what I have to say...

**Comment by koshalt** [comment]
test this please #insanity

**Comment by frankhuster** [comment]
test this please

**Comment by frankhuster** [comment]
@koshalt [I added a build step](http://ci.motechproject.org/job/NMS/jobConfigHistory/showDiffFiles?timestamp1=2015-07-31_21-34-59&timestamp2=2015-08-13_13-36-11) to delete datanucleus.properties and that seemed to have fixed it...

**Pull request merged**
