### PR TITLE
pull request test

### PR DESCRIPTION
**Pull request by kkaczmarczyk**

### CODE REVIEW

**Comment by motech-github** [comment]
Can one of the admins verify this patch?

**Comment by frankhuster** [comment]
ok to test

**Comment by frankhuster** [comment]
ok to test

**Comment by frankhuster** [comment]
ok to test

On Fri, Aug 28, 2015 at 2:10 AM, motech-github <notifications@github.com>
wrote:

> Can one of the admins verify this patch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/pull/573#issuecomment-135700146>
> .
>



-- 
Frank Huster
Mobile Health Innovations
Grameen Foundation
+1.206.325.6690 x201

**Comment by koshalt** [comment]
test this please

**Comment by koshalt** [comment]
test this please

**Pull request closed without merging**
