### PR TITLE
Implemented test case NMS_FT_12, 13, 14, 15

### PR DESCRIPTION
**Pull request by nmsyogesh**
JIRA bug raised at https://applab.atlassian.net/browse/NMS-192

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by frankhuster** [comment]
please merge

**Comment by srivastavaAbhi** [comment]
merged with master

**Comment by srivastavaAbhi** [comment]
Tracked with branch NMS.FT.KILKARICONTROLLERIT.
So closing this request.

**Pull request closed without merging**
