### PR TITLE
Soft launch bugfix

### PR DESCRIPTION
**Pull request by koshalt**
Fixes NIP-184 with query update for fresh calls

### CODE REVIEW

**Comment by koshalt** [comment]
test this please

**Comment by koshalt** [comment]
test this please

**Comment by koshalt** [comment]
weird. the first build failed because of datetime boundary with the tests running over midnight. The second run failed due to divine intervention. The third passed because.. well, it should have

**Comment by frankhuster** [comment]
LGTM, ok to merge

**Pull request merged**
