### PR TITLE
Fixes NIP-94

### PR DESCRIPTION
**Pull request by larubbio**
If there is an IVR originated subscriber, when the mcts upload comes, update the subscriber.

### CODE REVIEW

**Comment by frankhuster** [comment]
You gotta use `findByNumber` instead of `findByCallingNumber` now.

On Wed, Sep 9, 2015 at 11:12 AM, Rob LaRubbio <notifications@github.com>
wrote:

> If there is an IVR originated subscriber, when the mcts upload comes,
> update the subscriber.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/motech-implementations/mim/pull/585
> Commit Summary
>
>    - Fixes NIP-94
>
> File Changes
>
>    - *M*
>    kilkari/src/main/java/org/motechproject/nms/kilkari/service/impl/SubscriberServiceImpl.java
>    <https://github.com/motech-implementations/mim/pull/585/files#diff-0>
>    (7)
>    - *M*
>    testing/src/test/java/org/motechproject/nms/testing/it/kilkari/MctsBeneficiaryImportServiceBundleIT.java
>    <https://github.com/motech-implementations/mim/pull/585/files#diff-1>
>    (24)
>
> Patch Links:
>
>    - https://github.com/motech-implementations/mim/pull/585.patch
>    - https://github.com/motech-implementations/mim/pull/585.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/pull/585>.
>



-- 
Frank Huster
Mobile Health Innovations
Grameen Foundation
+1.206.325.6690 x201

**Comment by frankhuster** [comment]
That doesn't make any sense. I changed the code to use `findByNumber` yet the build breaks on `findByCallingNumber` what gives?!?

ps: should've never put my finger in this...

**Comment by larubbio** [comment]
Let's try this again.  YOU have to bring findByCallingNumber back.[image:
Inline image 1]

**Comment by koshalt** [comment]
lgtm

**Comment by larubbio** [comment]
Let's try this again.  YOU have to bring findByCallingNumber back.

**Pull request merged**
