### PR TITLE
Fixes NIP-60 (really)

### PR DESCRIPTION
**Pull request by larubbio**
If the user needs the welcome message, set that as the filename.

@llavoie This feels wrong to me.  First, the ticket is hard to follow.  Once it was decided that the actual issue was something different then the description should be updated.  As far as I can tell this "fixes" it.  Although it seems odd that the user will call and only hear the week 1/welcome message when the actual message is week 5 or something else.  Shouldn't we return two messages, the week 1/welcome and the actual message?

### CODE REVIEW

**Comment by llavoie** [comment]
Yeah, I disagree with the spec for this. But also, as far as I can tell, this fix won't actually do what is being asked. We're supposed to play the welcome message even if the user has already heard it through IVR (i.e. needsWelcomeMessage would be false in this case), as long as it's the user's first week subscribed to the service.

**Comment by larubbio** [comment]
Ok, do you want to take it over?

**Comment by llavoie** [comment]
The reason I haven't taken it yet is that I haven't thought up a good fix. :) But I'll stew on it.

**Comment by larubbio** [comment]
I can keep it if you want.

**Comment by llavoie** [comment]
Presumably we could add a field for the "activationDate" (i.e. the date the subscription was activated) in addition to the startDate (i.e. the date corresponding to "week 1" of the subscription pack messages) -- and compare these when handling inbox requests. Unless you have an cleverer ideas. I can do this or you -- don't care.

**Comment by larubbio** [comment]
Why don't you take it.  I'll look at another ticket.

**Comment by llavoie** [comment]
CR please

**Comment by larubbio** [comment]
lgtm

**Pull request merged**
