### PR TITLE
added test case NMS_FT_138, NMS_FT_139 on NMS.FT.138.139 branch.

### PR DESCRIPTION
**Pull request by srivastavaAbhi**
FT cases 138 and 139 added

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by frankhuster** [comment]
ok to test

**Comment by srivastavaAbhi** [comment]
test this please

**Comment by frankhuster** [comment]
ok to test

**Comment by srivastavaAbhi** [comment]
@frankhuster : Tested and merged with master

**Comment by frankhuster** [comment]
ok to test

**Comment by frankhuster** [comment]
test this please

**Pull request merged**
