### PR TITLE
Fixes #476

### LINKED ISSUE #476: Call Details fields needed for reports
List of parameters that are required in the Kilkari Reports but missing for the OBD Call Details and Call data:
 
Call Start DateTime ,
Call End DateTime ,
FilePlayed Start DateTime,
FilePlayed End DateTime,
Operator
DurationInPulse

### PR DESCRIPTION
**Pull request by frankhuster**
Now makes a copy of the complete CDR in a new CallDetailRecord (nms_imi_cdrs) table for reporting purposes.

### CODE REVIEW

**Comment by larubbio** [comment]
ok to test

**Comment by larubbio** [comment]
lgtm waiting for build to finish

**Comment by larubbio** [comment]
Does this also fix NIP-63?

**Comment by larubbio** [comment]
ok to test

**Comment by frankhuster** [comment]
Also fixes NIP-63

**Comment by larubbio** [comment]
Any idea why all tests have started failing?

**Comment by frankhuster** [comment]
Weird, something to do with platform?

**Comment by frankhuster** [comment]
ok to test

**Pull request merged**
