### PR TITLE
Implemented FT_35 and FT_186

### PR DESCRIPTION
**Pull request by AnkitGaurNms**
Implemented FT_35 and FT_186

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by frankhuster** [comment]
ok to test

**Comment by frankhuster** [comment]
ok to test

**Comment by frankhuster** [comment]
Great work!
The build legitimately fails because it looks like it may be a bug in KilkariController.java
What should we do in this case?
Should the person who wrote the FT - @AnkitGaurNms in this case - directly contact the dev responsible for this part of the code (using git blame?)
Or should we label this issue with something like 'Code defect uncovered by FT'?

**Comment by llavoie** [comment]
The test team has been creating bugs in Jira for issues that they find. If
the test itself looks good, we should have Ankit mark it with @Ignore for
now so that it doesn't cause build failures, and merge the PR. Including
the Jira ticket number in a comment would be great too.

On Thu, Jun 4, 2015 at 10:31 AM, Frank Huster <notifications@github.com>
wrote:

> Great work!
> The build legitimately fails because it looks like it may be a bug in
> KilkariController.java
> What should we do in this case?
> Should the person who wrote the FT - @AnkitGaurNms
> <https://github.com/AnkitGaurNms> in this case - directly contact the dev
> responsible for this part of the code (using git blame?)
> Or should we label this issue with something like 'Code defect uncovered
> by FT'?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/pull/308#issuecomment-108983641>
> .
>



-- 
Lauren Lavoie
Software Development Manager, Mobile Health Innovations
Grameen Foundation
2101 4th Ave | Suite 1550 | Seattle, WA 98121
206-325-6690 ext 254
llavoie@grameenfoundation.org | Skype:laurenlavoie
Facebook <http://www.facebook.com/StopPovertyNow>│Twitter
<http://twitter.com/grameenfdn>│YouTube
<http://www.youtube.com/user/grameen?blend=6&ob=5> | www.motechsuite.org
*Connecting the World's Poor to Their Potential*

**Comment by frankhuster** [comment]
Cool, @AnkitGaurNms did you get that? Looks like what's left for you to do is:

- add @Ignore
- add comment with http link to the JIRA issue
- commit & push again

Then we'll merge this pull request into master.

Thanks!

**Comment by larubbio** [comment]
Did we also decide to rename the FT methods?  From looking at this and the jenkins build I have no idea what was being tested.

**Comment by frankhuster** [comment]
The method name corresponds to the test case number (in the excel
spteadsheet) and should have a comment which is a copy of the description
of the test case (copy/pasted from the spreadsheet)

On Thu, Jun 4, 2015 at 10:53 AM, Rob LaRubbio <notifications@github.com>
wrote:

> Did we also decide to rename the FT methods? From looking at this and the
> jenkins build I have no idea what was being tested.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/pull/308#issuecomment-108990786>
> .
>



-- 
Frank Huster
Mobile Health Innovations
Grameen Foundation
+1.206.325.6690 x201

**Pull request merged**
