### PR TITLE
Fixes NMS-247

### PR DESCRIPTION
**Pull request by larubbio**

### CODE REVIEW

**Comment by koshalt** [comment]
lgtm

**Comment by koshalt** [comment]
What is going on with our CI?

**Comment by koshalt** [comment]
Also, my mom just used lol in a text for the first time today. it was cool. :laughing: LOL

**Comment by frankhuster** [comment]
Your mom is _so cool_ !!!

On Thu, Jul 23, 2015 at 8:29 PM, kosh <notifications@github.com> wrote:

> Also, my mom just used lol in a text for the first time today. it was
> cool. [image: :laughing:] LOL
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/pull/528#issuecomment-124310099>
> .
>



-- 
Frank Huster
Mobile Health Innovations
Grameen Foundation
+1.206.325.6690 x201

**Comment by larubbio** [comment]
ok to test

**Comment by larubbio** [comment]
So she just used lol, how many times has she texted wtf or smh to you?

**Comment by koshalt** [comment]
not yet...but I'm guessing its not too far away

**Comment by larubbio** [comment]
ok to test

**Pull request merged**
