### PR TITLE
Added spring-mvc unit test

### PR DESCRIPTION
**Pull request by kammad**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by larubbio** [comment]
ok to test.

**Comment by larubbio** [comment]
test this please.

**Comment by larubbio** [comment]
fixes #60

**Comment by frankhuster** [comment]
How is #60 fixed by this?

**Comment by larubbio** [comment]
This code creates a unit test for BaseController and mocks kilkariService
so it throws an exception.  It then verifies that the exception was thrown
and that the status is Internal Server error.

Are you expecting it to do something different?

**Comment by frankhuster** [comment]
Ah, cool!!!

I thought you were using kammad as a test for fake checkins.
I didn't really look at the actual changes, my bad.

**Pull request merged**
