### PR TITLE
implemented test cases 98, 99, 100

### PR DESCRIPTION
**Pull request by nmsyogesh**
JIRA issue is similar to https://applab.atlassian.net/browse/NMS-187
Added the details of the error into description of the issue.

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by frankhuster** [comment]
please merge

**Comment by srivastavaAbhi** [comment]
merged with master

**Comment by srivastavaAbhi** [comment]
Tracked with branch NMS.FT.KILKARICONTROLLERIT.
So closing this request.

**Pull request closed without merging**
