### PR TITLE
Extracting the urgent parts of PR #333

### PR DESCRIPTION
**Pull request by llavoie**
... but this doesn't appear to be enough

### CODE REVIEW

**Comment by llavoie** [comment]
@larubbio I just grabbed the table name change part of PR #333 but the UserControllerBundleITs still fail. What else are we missing?

**Comment by larubbio** [comment]
What is the failure?

**Comment by llavoie** [comment]
Tests run: 234, Failures: 4, Errors: 0, Skipped: 6, Time elapsed: 181.537 sec <<< FAILURE! - in org.motechproject.nms.testing.it.IntegrationTests
testKilkariUserRequestNoLanguage(org.motechproject.nms.testing.it.api.UserControllerBundleIT)  Time elapsed: 0.336 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...uageLocationCodes":[["50"]],"subscriptionPackL...> but was:<...uageLocationCodes":[[]],"subscriptionPackL...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.motechproject.nms.testing.it.api.UserControllerBundleIT.testKilkariUserRequestNoLanguage(UserControllerBundleIT.java:778)

testKilkariNonexistentUserRequest(org.motechproject.nms.testing.it.api.UserControllerBundleIT)  Time elapsed: 0.181 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...uageLocationCodes":[["50"]],"subscriptionPackL...> but was:<...uageLocationCodes":[[]],"subscriptionPackL...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.motechproject.nms.testing.it.api.UserControllerBundleIT.testKilkariNonexistentUserRequest(UserControllerBundleIT.java:802)

testGetUserDetailsUnknownUser(org.motechproject.nms.testing.it.api.UserControllerBundleIT)  Time elapsed: 0.149 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...uageLocationCodes":[["99","88"]],"currentUsageInPul...> but was:<...uageLocationCodes":[[]],"currentUsageInPul...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.motechproject.nms.testing.it.api.UserControllerBundleIT.testGetUserDetailsUnknownUser(UserControllerBundleIT.java:1028)

testFlwUserRequestWithoutServiceUsage(org.motechproject.nms.testing.it.api.UserControllerBundleIT)  Time elapsed: 0.212 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<...uageLocationCodes":[["99"]],"currentUsageInPul...> but was:<...uageLocationCodes":[[]],"currentUsageInPul...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.motechproject.nms.testing.it.api.UserControllerBundleIT.testFlwUserRequestWithoutServiceUsage(UserControllerBundleIT.java:830)

**Comment by llavoie** [comment]
We're making progress on #333 so this won't be needed.

**Pull request closed without merging**
