### PR TITLE
Implemented NMS_FT_39,40,41,42,43,44,45,46,47,48

### PR DESCRIPTION
**Pull request by kanchannms**
The test case are very similar. SO they have been put on same branch.

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by koshalt** [comment]
ok to test

**Comment by nmsyogesh** [comment]
Hi,

As the name of the branch was a little wrong, I have created a new branch and deleted this one. I'll raise the pull request accordingly. The branch was not covering test case no 48.

**Comment by nmsyogesh** [comment]
The new branch is at https://github.com/motech-implementations/mim/commits/NMS.FT.39.40.41.42.43.44.45.46.47

**Pull request closed without merging**
