### PR TITLE
Implemented NMS_FT_75

### PR DESCRIPTION
**Pull request by AnkitGaurNms**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by frankhuster** [comment]
ok to test

On Thu, Jun 4, 2015 at 6:45 AM, motech-gerrit <notifications@github.com>
wrote:

> Can one of the admins verify this patch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/pull/303#issuecomment-108903283>
> .
>



-- 
Frank Huster
Mobile Health Innovations
Grameen Foundation
+1.206.325.6690 x201

**Comment by frankhuster** [comment]
ok to test

**Comment by frankhuster** [comment]
ok to test

**Comment by frankhuster** [comment]
ok to test

**Comment by frankhuster** [comment]
ok to test

**Pull request merged**
