### PR TITLE
Adding sms reference number for MA reporting

### PR DESCRIPTION
**Pull request by koshalt**
Adding sms reference number for reporting

### CODE REVIEW

**Comment by frankhuster** [comment]
How about adding a test that uses `smsReferenceNumber`?

**Comment by koshalt** [comment]
Why? is it because you don't trust me?

**Comment by koshalt** [comment]
How about I use it in a sentence instead? 
"I added code for smsReference" .

**Comment by frankhuster** [comment]
LGTM

**Pull request merged**
