### PR TITLE
Fixes #131

### LINKED ISSUE #131: NMS.GEN.BKUP.001 - Data retention rules
The NMS system shall continue to maintain FLW/Beneficiary data for 6 weeks within its internal database once the corresponding record is marked Invalid (for FLW) or marked deactivated/completed (for beneficiary).  

For this purpose, the NMS system shall maintain the timestamp at which the corresponding record was marked invalid or deactivated/completed.

NMS shall not permit deletion of any record marked invalid or deactivated/completed record till 6 weeks of such activity.

### PR DESCRIPTION
**Pull request by larubbio**
Add a pre-delete lifecycle listener that verifies a subscription has been closed at least 6 weeks
 before it can be deleted.

### CODE REVIEW

**Comment by llavoie** [comment]
Your fix looks ok to me for subscriptions. Do you plan to handle the FLW deletion case (also described in #131) with a separate PR?

**Comment by larubbio** [comment]
No, I had forgotten about the other half of the issue. :)  I'll add that in
and then ask for review again.

**Comment by larubbio** [comment]
@llavoie @frankhuster @koshalt Come 'n get it!

**Comment by koshalt** [comment]
slte

Onit

**Comment by koshalt** [comment]
lgtm

**Pull request merged**
