### PR TITLE
Remove mobile-kunji bundle

### PR DESCRIPTION
**Pull request by llavoie**
We don't need this bundle because all Kunji logic is handled by the API and Language modules.

### CODE REVIEW

**Comment by frankhuster** [comment]
LGTM

**Comment by llavoie** [comment]
Ummm, @frankhuster, I think you closed this without merging it.

**Comment by frankhuster** [comment]
Oopsie.
What do I do now?

**Comment by frankhuster** [comment]
I know what I do, I wait for it to build again and then merge it before closing it...

**Comment by llavoie** [comment]
Haha, ok, the build passed so I went ahead and merged.

**Pull request merged**
