### PR TITLE
Fixes #399

### LINKED ISSUE #399: KK - Never need to check for whitelisting
From Pankaj/Saurabh:
>for Kilkari there will not be whitelisting services.

### PR DESCRIPTION
**Pull request by frankhuster**

### CODE REVIEW

**Comment by llavoie** [comment]
Should this be closed?

**Comment by llavoie** [comment]
Hey @larubbio - yeah, we agreed that this was not the right fix, that's why we didn't merge it. There was a mail thread with Saurabh that we all had different interpretations of...

**Comment by larubbio** [comment]
@llavoie Then can we close #399?

**Comment by llavoie** [comment]
I'm not sure. I'll dig up the mail thread and forward to you -- depending on how you interpret it we can decide whether there's any work to do.

**Pull request closed without merging**
