### PR TITLE
Fixes #13 & fixes #14

### LINKED ISSUE #13: api/obd - CDR File Notification

### LINKED ISSUE #14: api/obd - FileProcessedStatus Notification

### PR DESCRIPTION
**Pull request by llavoie**
Adds more test cases for CDR Notification Request and implements File Processed Request

### CODE REVIEW

**Comment by frankhuster** [comment]
Looks good & builds on my machine. I'll wait for the CI to complete successfully and will merge.

**Comment by frankhuster** [comment]
Hmm, the CI failed...

**Comment by larubbio** [comment]
"The forked VM terminated without properly saying goodbye."

How rude.

**Comment by frankhuster** [comment]
I can't seem to be able to re-trigger the build. Can you @larubbio ?

**Comment by larubbio** [comment]
16:43:04 #
16:43:04 # There is insufficient memory for the Java Runtime Environment to continue.
16:43:04 # Native memory allocation (malloc) failed to allocate 193986560 bytes for committing reserved memory.

I think it is ok to merge since it build locally for you.  If we get a failure like this again may be time to look at the ci container.

**Comment by frankhuster** [comment]
OK.

**Pull request merged**
