### PR TITLE
Test pull request plugin

### PR DESCRIPTION
**Pull request by larubbio**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by larubbio** [comment]
add to whitelist

**Comment by larubbio** [comment]
add to whitelist.

**Comment by larubbio** [comment]
add to whitelist.

**Comment by larubbio** [comment]
ok to test.

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by larubbio** [comment]
add to whitelist.

**Comment by koshalt** [comment]
thanks for the branch name

**Comment by larubbio** [comment]
It was the only way to be sure.

**Comment by koshalt** [comment]
but but... what if @frankhuster merges it??? http://goo.gl/RAbyna

**Comment by larubbio** [comment]
test this please.

**Pull request closed without merging**
