### PR TITLE
CR feedback from MCTS update work item

### PR DESCRIPTION
**Pull request by llavoie**
I haven't tested this or anything -- but I'm having the feeling I won't have a chance to finish it as it appears to be go time. :) If someone could take it over, that would be great.

### CODE REVIEW

**Comment by frankhuster** [comment]
YAY!!!!

**Comment by larubbio** [comment]
I'm sure it's just braxton hicks.  BACK TO WORK!!!!  :)

**Comment by koshalt** [comment]
go time and you pushed out a review first? 
bdss

**Comment by frankhuster** [comment]
Oh, and despite the minor contraction issue: lgtm!

**Pull request merged**
