### PR TITLE
Fixes deployment checks for subsciber data

### PR DESCRIPTION
**Pull request by koshalt**
Fixes #NIP-114 with checks for different scenarios described in the ticket. Either use MCTS data for deployment validation or use current circle if available.

### CODE REVIEW

**Comment by koshalt** [comment]
@frankhuster

**Comment by frankhuster** [comment]
lgtm, merge if/when the build passes?

**Comment by larubbio** [comment]
What's the over/under on the build passing?

**Comment by koshalt** [comment]
:+1: Roger that

**Comment by frankhuster** [comment]
happy

**Comment by koshalt** [comment]
@larubbio the build passed. Can I get paid now?

**Comment by larubbio** [comment]
no-no-no-very-bad-man-babu-bhatt-seinfeld-gifs-finger-wag

**Pull request merged**
