### PR TITLE
Fixes #134

### LINKED ISSUE #134: NMS.GEN.DEPL.004 - Maintain deployment status of services for each state
The NMS system shall maintain deployment status for each service (Deployed/Not-deployed) for each state. 

If any incoming request is received for a service from a state that is Not-deployed in that state, then appropriate error message shall be played (e.g. Service Not Available in the state) in standard Hindi.
Deployment state of service shall not influence the data upload procedures mentioned in Data & Language Management section for MA, MK and KK (i.e. FLW and beneficiary data upload for a given state shall be allowed even if the service is not deployed in the state).

### PR DESCRIPTION
**Pull request by llavoie**
Adds DeployedService entity to support selectively rolling out services per state. Also makes many of our API calls Transactional. Enables LanguageContrller test cases that were erroneously disabled.

### CODE REVIEW

**Comment by larubbio** [comment]
lgtm :)

**Comment by llavoie** [comment]
:)
It looks like the CI build failed yesterday and I haven't had time to look into it. All tests passed for me locally.

-----Original Message-----

**Comment by larubbio** [comment]
Detached field.  I put a fix in for it.

**Comment by frankhuster** [comment]
Forget about the failure. It's my bug.

**Comment by llavoie** [comment]
@larubbio your last two commits look fine to me.

**Pull request merged**
