### PR TITLE
implemented test cases 9, 10, 11

### PR DESCRIPTION
**Pull request by nmsyogesh**

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by nmsyogesh** [comment]
JIRA issue raised https://applab.atlassian.net/browse/NMS-184

**Comment by frankhuster** [comment]
please merge

**Comment by srivastavaAbhi** [comment]
Tracked with branch NMS.FT.KILKARICONTROLLERIT.
So closing this request.

**Pull request closed without merging**
