### PR TITLE
Composite keys for locations

### PR DESCRIPTION
**Pull request by frankhuster**
A location object code is unique amongst its sibling.
Two location objects can have the same code if they have different parent location objects.

### CODE REVIEW

**Comment by frankhuster** [comment]
ok to test

**Comment by llavoie** [comment]
Don't the various location *DataService lookups need to be updated as well? e.g. DistrictDataService.findByCode(code) can no longer be assumed to return a single District. So we'd need to change to findByCode(districtCode, stateCode) or similar.

**Comment by frankhuster** [comment]
I'm working on that right now.

On Fri, Jun 12, 2015 at 10:03 AM, Lauren Lavoie <notifications@github.com>
wrote:

> Don't the various location *DataService lookups need to be updated as
> well? e.g. DistrictDataService.findByCode(code) can no longer be assumed to
> return a single District. So we'd need to change to
> findByCode(districtCode, stateCode) or similar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/motech-implementations/mim/pull/383#issuecomment-111558441>
> .
>



-- 
Frank Huster
Mobile Health Innovations
Grameen Foundation
+1.206.325.6690 x201

**Comment by frankhuster** [comment]
Talk about Pandora's box...

**Comment by frankhuster** [comment]
No point building this just yet.

**Pull request closed without merging**
