### PR TITLE
245 course completion

### LINKED ISSUE #245: NMS.MA.COURSE.002 - Course completion criteria followup
There are a few edge cases in #149 that need some clarity and might have some follow up work based on the response from BBC.

These edge cases have to deal with when happens a when a user fails a course with his/her score and the resetting of bookmarks upon completion.

### PR DESCRIPTION
**Pull request by koshalt**
Fixes #245 

Fetching a bookmark after completion will reset it. This is based on confirmation from BBC

### CODE REVIEW

**Comment by koshalt** [comment]
ok to test

**Comment by koshalt** [comment]
ok to test

**Comment by koshalt** [comment]
test this please

**Comment by koshalt** [comment]
test this please

**Comment by koshalt** [comment]
ok to test

**Comment by frankhuster** [comment]
lgtm

**Pull request merged**
