### PR TITLE
Implemented FT_78, 82

### PR DESCRIPTION
**Pull request by AnkitGaurNms**
Implemented test cases FT_78 and FT_82

### CODE REVIEW

**Comment by motech-gerrit** [comment]
Can one of the admins verify this patch?

**Comment by frankhuster** [comment]
ok to test

**Comment by frankhuster** [comment]
lgtm

**Comment by frankhuster** [comment]
@AnkitGaurNms, please merge master (& fix conflicts, if any) rebuild & check is passes and then push again. Thanks!

**Comment by AnkitGaurNms** [comment]
Merged branch 'master' into this branch.

**Pull request merged**
