### PR TITLE
137

### PR DESCRIPTION
**Pull request by kamknitt**
Needs to wait for http://review.motechproject.org/#/c/5398/ to be merged.

The changes tracking feature works only if the setter method is invoked on the instance that is attached to the PM. It may be the case only for updates. The object must be first retrieved from the data service and then modified via setters - all within a transaction.
Because of this limitation, changes tracking for updates made via MDS UI doesn't work at the moment.

### CODE REVIEW

**Comment by larubbio** [comment]
Fixes #377
Fixes #137

**Comment by larubbio** [comment]
ok to test

**Comment by larubbio** [comment]
lgtm.  Waiting for build to complete.

**Comment by larubbio** [comment]
@kamknitt It looks like this commit is breaking some of the unit tests.  So those will need to be fixed before we can merge it.

**Comment by kamknitt** [comment]
@larubbio I've fixed the unit tests. They should be ok now.

**Pull request merged**
